include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    file_names: ignore
    use_full_hex_values_for_flutter_colors: ignore

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
